require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'MedicalApp' do
  config = use_native_modules!

  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.disabled,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # ✅ Remove boost from React Native's dependencies
 # pre_install do |installer|
  #  installer.pod_targets.each do |pod|
   #   if pod.name == 'boost'
   #     pod.remove_from_project
   #   end
   #  end
   # end
    

 

  # Other explicit dependencies
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  target 'MedicalAppTests' do
    inherit! :complete
  end

 post_install do |installer|
  react_native_post_install(installer, config[:reactNativePath])

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end

    # Bypass Boost conflicts by excluding it from certain architectures
    if target.name == 'boost'
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end



    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

